# Generated by Django 4.0.4 on 2022-05-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.FilePathField(path='/Users/chelloh/Documents/GitHub/waks-portfolio/tukoWaksBana/home/static/img'),
        ),
    ]
